image: Visual Studio 2017
version: 2.0.{build}
configuration: Debug
platform: Any CPU

install:
- ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex

build_script:
  - nuget restore -Verbosity quiet
  - msbuild /t:restore
  - msbuild /p:configuration=Debug /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
  - ps: Vsix-PushArtifacts | Vsix-PublishToGallery
